### ISSUE TITLE
invisible Button at centre of screen

### ISSUE THREAD

**Issue by AhsanAli65** [Ernest0-Production/ScreenNavigatorKit#1]
There is a button that appear at centre of screen and OS Accessibility focus on that button as well

**Comment by AhsanAli65** [comment]
<img width="460" alt="Screenshot 2023-12-26 at 3 25 32 PM" src="https://github.com/Ernest0-Production/ScreenNavigatorKit/assets/86588996/239f58f3-307b-4e8d-a1d9-6061dfc383cc">
 In Vision OS it becomes more prominent as OS has focus area on that button and this button appears on Mobile as well which s caught by Accessibility as its invisible in mobile

**Comment by Ernest0-Production** [comment]
Thanks for the feedback. Indeed, this is an incorrect condition. I will need to hide the visibility of the button through which the transition to the new screen is programmatically performed.

**Comment by AhsanAli65** [comment]
waiting for the updated edition thanks

**Comment by Ernest0-Production** [comment]
> waiting for the updated edition thanks

Fixed this in version 0.5.1
