### ISSUE TITLE
.definesPresentationContext() not found in updated version

### ISSUE THREAD

**Issue by AhsanAli65** [Ernest0-Production/ScreenNavigatorKit#2]
unable to build using .definesPresentationContext() as it was available in previous version

**Comment by Ernest0-Production** [comment]
Hello, this method has been removed. (I forgot to update the documentation)

To work with modal screens you need to use ModatlStackView (similar to NavigationStackView)

UPD: I've updated the documentation
https://github.com/Ernest0-Production/ScreenNavigatorKit/blob/main/README.md#2-modalstackcontroller
